### PR TITLE
fix(TCOMP-960): fix suggestions parameters mapping

### PR DESCRIPTION
**Pull request by gonchar-ivan**
**What is the current behavior?** (You can also link to an open issue here)

Suggestions action parameters were mapped to ElementParameter without respect to order in method declaration, which cause bugs in some cases.

**What is the new behavior?**

Suggestions action parameters were mapped to ElementParameter with respect to order in method declaration

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The code coverage on new code >75%
- [ ] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**

- [ ] Yes
- [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:
https://jira.talendforge.org/browse/TCOMP-960

### CODE REVIEW

**Comment by rmannibucau** [comment]
Can you add some tests with primitives, arrays and complex objects (not sure this case works with this impl reading the patch)

**Comment by gonchar-ivan** [comment]
There is another issue to check List and enum values https://jira.talendforge.org/browse/TCOMP-936
currently I use test component with different cases:
https://github.com/Talend/component-runtime-qa/blob/master/components/qa/src/main/java/org/talend/components/qa/actions/QASuggestionsDataset.java

It is a pain to write a unit-tests for integration plugin:
1. I failed to add libraries for mocking.
2. Eclipse doesn't recognize test files and source files due to it is plugin project
I tried to setup project for tests before. I wasted 2 days with no result (

I will try to implement some test-cases, however it is much more simple for me to test in Studio for the moment

**Comment by rmannibucau** [comment]
Ok
Let check with studio experts how to write tests before any new fix. The risk to break something else is way too high to skip tests now IMHO.

**Comment by gonchar-ivan** [comment]
Add tests with primitives and complex parameters. 
Arrays will be covered in next issue.

**Pull request merged**
