### PR TITLE
Fix(TDI-43939): Threads now handle interrupt calls, …

### PR DESCRIPTION
**Pull request by dmytrogrygorenko**
…  main thread waits for them to terminate.

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Please check if the PR fulfills these requirements**

- [X] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The code coverage on new code >75%
- [X] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**

- [ ] Yes
- [X] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by gonchar-ivan** [comment]
After a call with Dmtyro Chmyga and Dmyrto Grygorenko we decided to check in debug how bulk process behave and if new thread may finish without interrupt
(It's not clear for us why interrupt() was used originally)

**Comment by wwang-talend** [comment]
if no any bug here,  only think it's a "wrong" usage, not advice to change the code here, as :
interrupt avoid hold and block
join make hole and block
will check the reason

**Comment by wwang-talend** [comment]
https://www.talendforge.org/trac/tos now can't open it, no way to check the history now

**Comment by wwang-talend** [comment]
https://stackoverflow.com/questions/19909217/how-to-abort-a-blocking-process-getinputstream-read-with-close
maybe the reason

**Comment by wwang-talend** [comment]
i do some simple google, find some risk here :
https://community.oracle.com/thread/1145291
and yes, not 100% same case, but prove the risk, and also i keep my first advice,not advice to fix it if no bug in the background.

**Comment by wwang-talend** [comment]
will check it more

**Review by gonchar-ivan — DISMISSED** [review]

**Review by mbasiuk-talend — APPROVED** [review]

**Pull request merged**
