### PR TITLE
TDI-40351: Allow using different schema while using existing connection

### PR DESCRIPTION
**Pull request by jlolling**
**What is the current behavior?** (You can also link to an open issue here)
The component use the schema given by the tPostgresqlConnection component

**What is the new behavior?**
The component can use optionally a alternate schema

**Please check if the PR fullfills these requirements**
- [x] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The code coverage on new code >75%
- [ ] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

**Other information**:
It is a request from a customer.

### CODE REVIEW

**Comment by dmytro-sylaiev** [comment]
Will be done in https://github.com/Talend/tdi-studio-se/pull/4007

**Comment by jlolling** [comment]
The conflict is very small and actually not really a conflict. Simply merge the properties and thats it.

**Comment by jlolling** [comment]
> No need in this PR

Why do you think we do not need this pull request? Is this feature already added in a different way?

**Comment by dmytro-sylaiev** [comment]
This feature will be in 7.3.1 and already implemented in the related PR for this component (and a lot of others)

**Comment by pteyssier** [comment]
@dmytro-sylaiev I explained here https://wiki.talend.com/display/rd/How+to+integrate+a+pull+request how to integrate contributors PR without losing the track of their participation. Too late now but it would be nice to follow those steps next time

**Pull request closed without merging**
