### PR TITLE
fix(TDI-47385): tMap error when tenary operator is used

### PR DESCRIPTION
**Pull request by dochkas-talend**
Added parentheses so that user don't add them manually

### CODE REVIEW

**Review by ozhelezniak-talend — APPROVED** [review]
LGTM
How does it work on 6.3?

**Comment by dochkas-talend** [comment]
Looks like the regression happens after this fix https://jira.talendforge.org/browse/TDI-43105

**Review by ozhelezniak-talend — APPROVED** [review]
LGTM

**Comment by dochkas-talend** [comment]
Now it's good to go

**Review by ozhelezniak-talend — APPROVED** [review]
LGTM

**Pull request merged**
