### PR TITLE
Dshekera/tdi 42230 tdi 26493 t file copy larger file failed java11

### PR DESCRIPTION
**Pull request by dmytroshekera**
**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The code coverage on new code >75%
- [ ] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**

- [ ] Yes
- [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by wwang-talend** [comment]
seems forget to remove build.xml for ant

**Comment by wwang-talend** [comment]
how about this fix(i didn't test it) :
{code}
import sun.nio.ch.DirectBuffer;
...
@SuppressWarnings("unchecked")
    private static void clean(final Object buffer) throws Exception {
        AccessController.doPrivileged(new PrivilegedAction() {

            public Object run() {
            	if(!(buffer instanceof DirectBuffer)) {
            		return null;
            	}
            	
                try {
                	DirectBuffer db = (DirectBuffer)buffer;
                	db.cleaner().clean();
                } catch (Exception e) {
                    e.printStackTrace();
                }
                return null;
            }
        });
    }
{code}
can compiler in java8 and java 11, though impimport sun.nio.ch.DirectBuffer...but better than reflect which need to add option

**Comment by dmytroshekera** [comment]
> remove build.xml for ant

remove build.xml and call from parent buildall.xml

**Comment by wwang-talend** [comment]
how about the code advice? which can avoid to add the java option.

**Pull request closed without merging**
